name: main

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check gcc version
        run: gcc version
      - name: Install curl-dev
        run: sudo apt-get install libcurl4-openssl-dev
      - name: Run build
        run: cd libnss-json && make lib
